ref:
  # Reference genome
  reference: "/work/jawlab/kivanc/PeanutRnaSeq/reference/arahy.Tifrunner.gnm1.KYV3.genome_main.fa"
  # Reference gene models
  annotation: "/work/jawlab/kivanc/PeanutRnaSeq/reference/arahy.Tifrunner.gnm1.ann1.CCJH.gene_models_main.gff3"
  
  sj: "/work/jawlab/kivanc/PeanutRnaSeq/reference/SJ.filtered.tab"

  transcript: "/work/jawlab/kivanc/PeanutRnaSeq/reference/arahy.Tifrunner.gnm1.ann1.CCJH.transcript.fa"

  reference2: "/work/jawlab/kivanc/PeanutRnaSeq/referenceV2/arahy.Tifrunner.gnm2.J5K5.genome_main.fa"

  transcript2: "/work/jawlab/kivanc/PeanutRnaSeq/referenceV2/arahy.Tifrunner.gnm2.ann1.4K0L.transcript.fa"

  annotation2: "/work/jawlab/kivanc/PeanutRnaSeq/referenceV2/arahy.Tifrunner.gnm2.gene_models.gtf"

  star_index: "/work/jawlab/kivanc/PeanutRnaSeq/StarIndex"

files:
  raw: "/work/jawlab/kivanc/PeanutRnaSeq/data/fastq"

  rRNA: "/work/jawlab/kivanc/PeanutRnaSeq/rRNA/rrna.fa"

trimming:
  # skip trimming: false or true
  skip: false

decontamination:
  skip: false

alignment:
  activate: true

star:
  activate: true

featurecounts:
  activate: false

rsem:
  activate: true
  rsemindex: results/05_quantification/05a_rsem/rsem_index/tifrunner
  genes: "results/05_quantification/05a_rsem/genes"

htseq:
  activate: true

alignment_free:
  activate: true

kallisto:
  activate: true

salmon:
  activate: true

salmon_mode:
  mapping_mode: true
  alignment_mode: false

samples:
  meristem: meristem.tsv
  leaf: leaf.tsv